name: test
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: check out payment
      uses: actions/checkout@v2
      with:
        path: './payment'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: build common
      run: cd common && mvn clean install
    - name: install common
      run: cd common && mvn install:install-file -Dfile=./target/common-1.0-SNAPSHOT.jar  -DpomFile=./pom.xml
    - name: verify payment
      run: cd payment && mvn clean verify
